export const dropdownItemsCountry = [
  { href: '/news/country/ae', text: 'ОАЭ' },
  { href: '/news/country/ar', text: 'Аргентина' },
  { href: '/news/country/at', text: 'Австрия' },
  { href: '/news/country/au', text: 'Австралия' },
  { href: '/news/country/be', text: 'Бельгия' },
  { href: '/news/country/bg', text: 'Болгария' },
  { href: '/news/country/br', text: 'Бразилия' },
  { href: '/news/country/ca', text: 'Канада' },
  { href: '/news/country/ch', text: 'Швейцария' },
  { href: '/news/country/cn', text: 'Китай' },
  { href: '/news/country/co', text: 'Колумбия' },
  { href: '/news/country/cu', text: 'Куба' },
  { href: '/news/country/cz', text: 'Чехия' },
  { href: '/news/country/de', text: 'Германия' },
  { href: '/news/country/eg', text: 'Египет' },
  { href: '/news/country/fr', text: 'Франция' },
  { href: '/news/country/gb', text: 'Великобритания' },
  { href: '/news/country/gr', text: 'Греция' },
  { href: '/news/country/hk', text: 'Гонконг' },
  { href: '/news/country/hu', text: 'Венгрия' },
  { href: '/news/country/id', text: 'Индонезия' },
  { href: '/news/country/ie', text: 'Ирландия' },
  { href: '/news/country/il', text: 'Израиль' },
  { href: '/news/country/in', text: 'Индия' },
  { href: '/news/country/it', text: 'Италия' },
  { href: '/news/country/jp', text: 'Япония' },
  { href: '/news/country/kr', text: 'Южная Корея' },
  { href: '/news/country/lt', text: 'Литва' },
  { href: '/news/country/lv', text: 'Латвия' },
  { href: '/news/country/ma', text: 'Марокко' },
  { href: '/news/country/mx', text: 'Мексика' },
  { href: '/news/country/my', text: 'Малайзия' },
  { href: '/news/country/ng', text: 'Нигерия' },
  { href: '/news/country/nl', text: 'Нидерланды' },
  { href: '/news/country/no', text: 'Норвегия' },
  { href: '/news/country/nz', text: 'Новая Зеландия' },
  { href: '/news/country/ph', text: 'Филиппины' },
  { href: '/news/country/pl', text: 'Польша' },
  { href: '/news/country/pt', text: 'Португалия' },
  { href: '/news/country/ro', text: 'Румыния' },
  { href: '/news/country/rs', text: 'Сербия' },
  { href: '/news/country/ru', text: 'Россия' },
  { href: '/news/country/sa', text: 'Саудовская Аравия' },
  { href: '/news/country/se', text: 'Швеция' },
  { href: '/news/country/sg', text: 'Сингапур' },
  { href: '/news/country/si', text: 'Словения' },
  { href: '/news/country/sk', text: 'Словакия' },
  { href: '/news/country/th', text: 'Таиланд' },
  { href: '/news/country/tr', text: 'Турция' },
  { href: '/news/country/tw', text: 'Тайвань' },
  { href: '/news/country/ua', text: 'Украина' },
  { href: '/news/country/us', text: 'США' },
  { href: '/news/country/ve', text: 'Венесуэла' },
  { href: '/news/country/za', text: 'ЮАР' },
];

export const dropdownItemsTime = [
  { href: '/news/date/today', text: 'За сегодня' },
  { href: '/news/date/past7days', text: 'Последние 7 дней' },
  { href: '/news/date/month', text: 'За текущий месяц' },
  { href: '/news/date/year', text: 'За текущий год' },
];

export const dropdownItemsCategory = [
  { href: '/news/category/business', text: 'Бизнес' },
  { href: '/news/category/entertainment', text: 'Развлечения' },
  { href: '/news/category/general', text: 'Общее' },
  { href: '/news/category/health', text: 'Здоровье' },
  { href: '/news/category/science', text: 'Наука' },
  { href: '/news/category/sports', text: 'Спорт' },
  { href: '/news/category/technology', text: 'Технологии' },
];
