# Generated by Django 4.2.6 on 2023-12-20 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(help_text='Название категории', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(help_text='Название города', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(help_text='Название страны', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(help_text='Название источника', max_length=50)),
                ('source_link', models.CharField(help_text='Ссылка на источник', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('system_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название системы', max_length=10)),
                ('version', models.CharField(help_text='Версия системы', max_length=10)),
                ('last_update', models.DateField(auto_now=True, help_text='Дата последнего обновления системы')),
            ],
            options={
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(help_text='Логин пользователя', max_length=50)),
                ('password', models.CharField(help_text='Пароль пользователя', max_length=50)),
                ('user_first_name', models.CharField(help_text='Имя пользователя', max_length=50)),
                ('user_last_name', models.CharField(help_text='Фамилия пользователя', max_length=50)),
                ('email', models.EmailField(help_text='Почта пользователя', max_length=100)),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], help_text='Системный доступ пользователя', max_length=20)),
                ('registration_date', models.DateField(auto_now=True, help_text='Дата регистрации пользователя')),
                ('last_login', models.DateField(auto_now=True, help_text='Дата последнего входа пользователя')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_aggregator_api.system')),
            ],
            options={
                'ordering': ['login', '-last_login'],
            },
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('user_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_category_name', models.CharField(help_text='Название пользовательской категории', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_aggregator_api.user')),
            ],
            options={
                'ordering': ['user_category_name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(help_text='Название региона', max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_aggregator_api.country')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Название новости', max_length=50)),
                ('description', models.TextField(help_text='Полный текст новости')),
                ('event_date', models.DateField(help_text='Дата произошедшего события')),
                ('publication_date', models.DateField(auto_now=True, help_text='Дата публикации')),
                ('categories', models.ManyToManyField(blank=True, related_name='news', to='news_aggregator_api.category')),
                ('cities', models.ManyToManyField(blank=True, related_name='news', to='news_aggregator_api.city')),
                ('countries', models.ManyToManyField(blank=True, related_name='news', to='news_aggregator_api.country')),
                ('regions', models.ManyToManyField(blank=True, related_name='news', to='news_aggregator_api.region')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_aggregator_api.source')),
            ],
            options={
                'ordering': ['title', '-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='FamousEvent',
            fields=[
                ('famous_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('famous_event_name', models.CharField(help_text='Название известного события', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_aggregator_api.category')),
            ],
        ),
        migrations.CreateModel(
            name='FamousDate',
            fields=[
                ('famous_date_id', models.AutoField(primary_key=True, serialize=False)),
                ('famous_date', models.DateField(auto_now=True, help_text='Известная дата')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_aggregator_api.category')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_aggregator_api.region'),
        ),
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('celebrity_id', models.AutoField(primary_key=True, serialize=False)),
                ('celebrity_first_name', models.CharField(help_text='Имя известного человека', max_length=50)),
                ('celebrity_last_name', models.CharField(help_text='Фамилия известного человека', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_aggregator_api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(blank=True, help_text='Изображения приклепленные к новости', null=True, upload_to='assets/images/')),
                ('videos', models.FileField(blank=True, help_text='Видео приклепленные к новости', null=True, upload_to='assets/images/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_aggregator_api.news')),
            ],
        ),
    ]
