# Generated by Django 4.2.7 on 2023-12-20 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news_aggregator_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True, help_text='Дата регистрации пользователя')),
                ('last_login', models.DateField(auto_now=True, help_text='Дата последнего входа пользователя')),
                ('groups', models.ManyToManyField(blank=True, help_text='Системный доступ пользователя', to='auth.group')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_aggregator_api.system')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
