# Generated by Django 4.2.7 on 2023-12-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_api', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Название новости', max_length=255),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_link',
            field=models.CharField(help_text='Ссылка на источник', max_length=255),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.CharField(help_text='Название источника', max_length=255),
        ),
    ]
