# Generated by Django 4.2.6 on 2023-12-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_api', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Политика', 'Политика'), ('Экономика', 'Экономика'), ('Технологии', 'Технологии'), ('Спорт', 'Спорт'), ('Наука и Здоровье', 'Наука и Здоровье'), ('Развлечения', 'Развлечения'), ('Криминал', 'Криминал')], help_text='Название категории', max_length=50),
        ),
    ]
