# Generated by Django 4.2.6 on 2023-12-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_api', '0002_usercategory_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publication_date', 'title']},
        ),
    ]
