# Generated by Django 4.2.7 on 2023-12-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_api', '0003_alter_news_title_alter_source_source_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='event_date',
            field=models.DateField(help_text='Дата произошедшего события', null=True),
        ),
    ]
