# Generated by Django 4.2.6 on 2023-12-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_api', '0003_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_link',
            field=models.CharField(help_text='Ссылка на источник', max_length=2500),
        ),
    ]
