# Generated by Django 4.2.6 on 2023-12-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_api', '0004_alter_news_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, help_text='Полный текст новости', null=True),
        ),
    ]
