# Generated by Django 4.2.6 on 2023-12-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_api', '0005_alter_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='images',
            field=models.CharField(blank=True, help_text='Изображения приклепленные к новости', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='videos',
            field=models.CharField(blank=True, help_text='Видео приклепленные к новости', max_length=255, null=True),
        ),
    ]
