# Generated by Django 4.2.6 on 2023-12-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_api', '0006_alter_asset_images_alter_asset_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='images',
            field=models.CharField(blank=True, help_text='Изображения приклепленные к новости', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='videos',
            field=models.CharField(blank=True, help_text='Видео приклепленные к новости', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Название новости', max_length=5000),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_link',
            field=models.CharField(help_text='Ссылка на источник', max_length=5000),
        ),
    ]
