# Generated by Django 4.2.6 on 2023-12-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_api', '0006_userprofile_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famousdate',
            name='famous_date',
            field=models.DateField(help_text='Известная дата'),
        ),
    ]
