# Generated by Django 4.2.6 on 2023-12-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_api', '0008_alter_asset_images_alter_asset_videos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='images',
            field=models.CharField(blank=True, help_text='Изображения приклепленные к новости', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='videos',
            field=models.CharField(blank=True, help_text='Видео приклепленные к новости', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Название новости', max_length=50000),
        ),
    ]
