# Generated by Django 4.2.6 on 2023-12-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_api', '0009_alter_asset_images_alter_asset_videos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.CharField(help_text='Название источника', max_length=500),
        ),
    ]
