# Generated by Django 4.2.6 on 2023-12-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator_api', '0010_alter_source_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_link',
            field=models.CharField(help_text='Ссылка на источник', max_length=1000),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.CharField(help_text='Название источника', max_length=1000),
        ),
    ]
